---
resources:
- name: resource-tutorial
  type: git
  check_every: 20s
  source:
    uri: https://github.com/CookieNotSession/twewcweightloss2018.git
    branch: master
- name: cloudfoundry
  type: cf
  source:
    api: https://api.system.mypcf.idv.tw
    username: allengreen
    password: qwerty
    organization: fet4IBM
    space: sit-sapce
    skip_cert_check: true
    

jobs:
- name: maven install
  public: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: maven-install
    file: resource-tutorial/mvn.yml
#- name: deploy-web
#  public: true
#  plan:
#  - get: resource-tutorial
#    trigger: true
#  - task: cfpush
  - put: cloudfoundry
    params:
      manifest: resource-tutorial/manifest.yml
      buildpack: java_buildpack_offline
#      path: resource-tutorial/target/twewcweightloss2018-1.0-SNAPSHOT.jar
#- name: cfpush
#  public: true
#  plan:
#  - get: resource-tutorial
#    trigger: true
#  - task: cfpush
#    file: resource-tutorial/cfpush.yml

