---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/CookieNotSession/twewcweightloss2018.git
    branch: master
- name: cloudfoundry
  type: cf
  source:
    api: https://api.system.mypcf.idv.tw
    username: allengreen
    password: qwerty
    organization: fet4IBM
    space: sit-sapce
    skip_cert_check: true
    

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: hello-world
    file: resource-tutorial/task_hello_world.yml
  - put: cloudfoundry
    params:
      manifest: resource-tutorial/manifest.yml
      buildpack: java_buildpack_offline
      path: target/twewcweightloss2018-1.0-SNAPSHOT.jar


